post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1ZXN0IiwiaWQiOiI2MmIwM2NiYWZmNjE1MzhjYmRhOWQ1OWYiLCJpYXQiOjE2NTU3MTcwNzN9.Hf1_D2z8WALFU-VJF0cOQ9zToh1XZSx-2dGQ-gPsad8

{
"title": "Promises chaining",
"author": "The Modern JavaScript Tutorial",
"url": "https://javascript.info/promise-chaining",
"likes": 8
}

###

get http://localhost:3001/api/blogs/62b0372983d8f42a44a005de


###
put http://localhost:3001/api/blogs/62b0372983d8f42a44a005de
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhbGlkIHVzZXIiLCJpZCI6IjYyYWU3YzQxNWY1OGU2NzUyYzdlYWY2NCIsImlhdCI6MTY1NTYxMDkzOH0.4G9maRYLKnojxQDdwZEo4IZEwXNwZtVVSwA2q09-_bM

{"title": "my edited post 555"}


###
delete http://localhost:3001/api/blogs/62b03ce5ff61538cbda9d5a3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1ZXN0IiwiaWQiOiI2MmIwM2NiYWZmNjE1MzhjYmRhOWQ1OWYiLCJpYXQiOjE2NTU3MTcwNzN9.Hf1_D2z8WALFU-VJF0cOQ9zToh1XZSx-2dGQ-gPsad8


### 
post http://localhost:3001/api/users
Content-Type: application/json

{
 "username": "star",
 "name": "Star",
 "password": "123"
 }

###
get http://localhost:3001/api/users

###
post http://localhost:3001/api/login
Content-Type: application/json

 {
 "username": "Guest",
 "password": "guestpassword1"
 }
