post http://localhost:8001/api/blogs
Content-Type: application/json

{
"title": "my blog 9999",
"author": "Me 79",
"url": "me.com",
"userId": "62a69d56183f7c2c6b53471d"
}

###

get http://localhost:8001/api/blogs


###
put http://localhost:3001/api/notes/629f108b994f375aa446c0af
Content-Type: application/json

{
"content": "VS Note 2",
"important": false
}

###
delete http://localhost:3001/api/notes/629f1212a3f5174f69a38f6b

### 
post http://localhost:8001/api/users
Content-Type: application/json

 {
 "username": "user",
 "name": "User User",
 "password": "user1password"
 }

###
get http://localhost:8001/api/users
