post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhbGlkIHVzZXIiLCJpZCI6IjYyYWU3YzQxNWY1OGU2NzUyYzdlYWY2NCIsImlhdCI6MTY1NTYwMjI1MX0.rhUAdQ9lsHlu8Unz1fqb8sVtD7Px7_boGyXY9l9yKKU

{
"title": "my authorized post",
"author": "Me 2",
"url": "me.com"
}

###

get http://localhost:8001/api/blogs


###
put http://localhost:3001/api/notes/629f108b994f375aa446c0af
Content-Type: application/json

{
"content": "VS Note 2",
"important": false
}

###
delete http://localhost:3001/api/notes/629f1212a3f5174f69a38f6b

### 
post http://localhost:3001/api/users
Content-Type: application/json

 {
 "username": "valid user",
 "name": "Valid user",
 "password": "user1password"
 }

###
get http://localhost:3001/api/users

###
post http://localhost:3001/api/login
Content-Type: application/json

 {
 "username": "valid user",
 "password": "user1password"
 }
